/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/NotFound': RouteRecordInfo<
      '/NotFound',
      '/NotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/story-map/[id]/[[section]]': RouteRecordInfo<
      '/story-map/[id]/[[section]]',
      '/story-map/:id/:section?',
      { id: ParamValue<true>, section?: ParamValueZeroOrOne<true> },
      { id: ParamValue<false>, section?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/story-map-2/': RouteRecordInfo<
      '/story-map-2/',
      '/story-map-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/story-map-2/[id]/[[section]]': RouteRecordInfo<
      '/story-map-2/[id]/[[section]]',
      '/story-map-2/:id/:section?',
      { id: ParamValue<true>, section?: ParamValueZeroOrOne<true> },
      { id: ParamValue<false>, section?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/NotFound.vue': {
      routes:
        | '/NotFound'
      views:
        | never
    }
    'src/pages/story-map/[id]/[[section]].vue': {
      routes:
        | '/story-map/[id]/[[section]]'
      views:
        | never
    }
    'src/pages/story-map-2/index.vue': {
      routes:
        | '/story-map-2/'
      views:
        | never
    }
    'src/pages/story-map-2/[id]/[[section]].vue': {
      routes:
        | '/story-map-2/[id]/[[section]]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
