name: Deploy Hazard Risk Dashboard and other static pages
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          cd gaia-viz-vue
          npm install
          npm run build

      - name: Prep staging folder
        run: |
          mkdir _site
          rsync -av --exclude='gaia-viz-vue' --exclude='_site' --exclude='.git' --exclude='.github' ./ ./_site/
          mkdir -p ./_site/gaia-dashboard
          cp -r ./gaia-viz-vue/dist/* ./_site/gaia-dashboard/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
  
